### ISSUE TITLE
Marvin v5.1.0 NNUE can not mate with N+B

### ISSUE THREAD

**Issue by tissatussa** [bmdanielsson/marvin-chess#10] opened 2021-07-21 14:22 UTC
when only a kNight and Bishop are on the board (plus 2 Kings) Marvin v5.1.0 NNUE can not mate !?

**Comment by bmdanielsson** [comment] 2021-07-21 15:26
This is without tablesbases, right? Do you have an example of a position that it fails to win?

**Comment by tissatussa** [comment] 2021-07-21 15:31
yes, without TBs.
eg. 8/1N6/8/3k1K2/8/8/1B6/8 b - - 0 1
White (Marvin v5.1.0 NNUE) should win this position ..

**Comment by bmdanielsson** [comment] 2021-07-21 16:10
I had Marvin play out the position against itself and like you said it has no clue how to win. But it's in good company. I did the same test with Stockfish 12 and it couldn't win either.

One thing that could be the cause for this (at least in the case of Marvin) is that training data for NNUE was generated with tablebases enabled and adjudication enabled. So training has never seen a position like this before. I have now changed to generating data with tablesbases disabled and no adjudication. It will be interesting to revisit this position when I have a new net and see if it helped.

**Comment by tissatussa** [comment] 2021-07-21 16:40
mmm .. i also did a test, using SF Cfish 12 without NNUE, and it CAN do the mate :

```
[Event "engine-vs-engine"]
[Site "?"]
[Date "2021.07.21"]
[White "SF CFish v12 no NNUE"]
[Black "Xiphos v0.6.1"]
[Result "1-0"]
[FEN "8/1N6/8/3k1K2/8/8/1B6/8 b - - 0 1"]
[GameDuration "00:17:21"]
[PlyCount "58"]
[SetUp "1"]
[TimeControl "720+5"]

1... Kc6 {-298.60/29 246s} 2. Na5+ {+M75/56 124s} Kc5 {-M66/17 26s}
3. Ke5 {+M61/51 0s} Kb6 {-M56/22 24s} 4. Bc3 {+M55/51 101s} Kc5 {-M52/29 19s}
5. Ke6 {+M53/49 16s} Kb5 {-M50/27 0.96s} 6. Kd5 {+M49/48 51s} Kb6 {-M48/25 14s}
7. Nc4+ {+M47/48 0s} Kc7 {-M46/26 14s} 8. Be5+ {+M45/47 21s} Kb7 {-M44/31 13s}
9. Kd6 {+M43/47 4.0s} Kb8 {-M42/31 21s} 10. Kc6+ {+M41/46 15s}
Ka8 {-M40/32 1.9s} 11. Nb6+ {+M39/46 8.3s} Ka7 {-M38/35 20s}
12. Bg3 {+M37/47 18s} Ka6 {-M36/35 13s} 13. Bb8 {+M35/47 0s} Ka5 {-M34/35 15s}
14. Nd5 {+M33/46 0s} Ka4 {-M32/36 14s} 15. Be5 {+M31/46 0s} Ka5 {-M30/36 14s}
16. Bd4 {+M29/45 8.7s} Ka6 {-M28/39 9.2s} 17. Nb4+ {+M27/45 4.6s}
Ka5 {-M26/36 12s} 18. Kc5 {+M25/45 1.1s} Ka4 {-M24/38 11s} 19. Kc4 {+M23/48 0s}
Ka5 {-M22/39 13s} 20. Bf2 {+M21/49 0.14s} Ka4 {-M20/42 14s}
21. Bb6 {+M19/50 2.1s} Ka3 {-M18/46 9.1s} 22. Nd3 {+M17/54 5.5s}
Ka4 {-M16/49 7.1s} 23. Nc5+ {+M15/56 13s} Ka3 {-M14/62 0.31s}
24. Kc3 {+M13/61 11s} Ka2 {-M12/76 96s} 25. Kc2 Ka3 {-M10/80 9.2s} 26. Ba5
Ka2 {-M8/99 0.51s} 27. Bb4 Ka1 {-M6/99 0.011s} 28. Nb3+ {+M5/245 0.003s}
Ka2 {-M4/99 0.010s} 29. Nc1+ {+M3/245 0.005s} Ka1 {-M2/99 0.010s}
30. Bc3# {White mates} 1-0
```

**Comment by bmdanielsson** [comment] 2021-07-21 19:15
Ok, I tested with CFish and it manages to win. I test with very fast time control so with a little more time SF will probably manage to win as well. I suspect that the key here is to be able to search deep enough to see which moves are draws and which aren't. SF in many cases has the same score for all winning moves and 0.00 for all others. Unfortunately Marvin only reaches about half the depth of SF in many of the relevant positions :(

But when playing around I did manage to find one bug in Marvin. When using NNUE Marvin fails to recognize draw by insufficient material. It probably doesn't matter in this endgame, but anyway.

**Comment by tissatussa** [comment] 2021-07-21 20:24
nice !
yes, i use 12 minutes per player per game .. why are engine programmers often performing fast time controls ?  Does ELO depend on it ?  Or is it used for training NNs ? In a regular engine-vs-engine game some delicate decisions could be made somewhere in the middle game, esp. with a closed centre, so i give thinktime to an engine : for me Marvin v5.1.0 acts good in such positions, it tries to keep pieces on the board and manages to "squeeze harmoniously".

**Comment by tissatussa** [comment] 2021-07-21 22:02
lately i discovered the test positions of Walter Eigenmann, see https://www.chessprogramming.org/Eigenmann_Rapid_Engine_Test and https://glarean-magazin.ch/2020/06/12/computerschach-the-engine-crackers-knacknuesse-fuer-schach-programme-hard-chess-puzzles/ (it's in German .. you can use the Google Translate button to read English)

i took one those positions and let several engines play against eachother .. it's about the second position on the page of my last link, Leela-vs-Stockfish : after Ne4 Nxb4 Qxb4! the position on the right arises :

![ice_chess12](https://user-images.githubusercontent.com/1109281/126565912-3425575d-43a3-476f-bd8c-568d217e6e24.png)

before: 2rqr1k1/pp1bbp1p/2n1p1pB/2N1P3/1PQp4/P4N2/5PP1/3RR1K1 w - - 0 2
after: 2rqr1k1/pp1bbp1p/4p1pB/4P3/1Q1pN3/P4N2/5PP1/3RR1K1 b - - 0 2

i let engines play in CuteChess .. all engines take the Q .. i discovered many things in this unbalanced position which White should be able to win, but it's not easy : Black might free himself and even win ..

playing White, Marvin v5.1.0 manages to never loose and rarely draw ! This is unique, even my SF 14 NNUE can not do that .. the game with SF SugaR-AI v2.20 NNUE holds the N+B position of this issue, that's why i wrote this issue ..
-PGNs attached-

[diagram_Qsac_games.zip](https://github.com/bmdanielsson/marvin-chess/files/6859032/diagram_Qsac_games.zip)

**Comment by bmdanielsson** [comment] 2021-07-22 08:35
Very interesting position, thanks for sharing. Nice to see that Marvin is performing well.

Regarding time controls it's more accurate to test with longer time controls. However when you want to verify that a change is an improvement you need to play a lot of games (several thousand) so you have to compromise. It turns out that using very fast time controls is accurate enough to give a good picture of how it performs at longer time controls. But in complicated positions like this it fails. NN also requires you to play a lot of games. You need to generate a lot of test data to train on and each training session generateres many differeent nets that you want to test.

**Comment by tissatussa** [comment] 2021-07-22 13:45
here's an update on how Marvin v5.1.0 NNUE performs against other strong engines : a few days ago my SF SugaR v2.20 NNUE made a draw with Black, but sometimes (!?) Marvin just wins .. there are a few good variations in this complex position, but the engine also encounters several moments which hold a few continuations with almost equal eval .. then the engine should have something like intuition to navigate the variations .. normally Marvin slowly enforces its position and tends not to exchange pieces, but your engine can also sacrifice at the right moment .. i feel it thrives towards positions, also endings, which are "most promising" according to its NN ..

i'm rather new to the NN thing .. although i experienced and read a lot .. but i'm not into some own engine dev like you .. even GitHub itself is new to me .. but i manage to compile engines and their devs, in several languages / compilers etc .. i learn a lot, using Linux .. so thank you for your long explanation !

so you can train a NN, or a set, regarding 1 position ?  Or a list of positions which are "alike" ?  Can i give input for an experimental training ?  Or is my mind to simple here ?

**Comment by bmdanielsson** [comment] 2021-07-22 15:42
Unfortunately it's not that simple. The main problem is that you have no direct control over what the network learns. The two main things you can control is the architecture of the net and the data you use for training. 

With data you can influence what it learns to some extent. For instance it will probably have a hard time understanding passed pawns if it has never seen positions that include passed pawns during training. But then the amount of positions including passed pawns has to be balanced compared to other positions otherwise it may play very well in positions with passed pawns but very poorly in other positions. With the architecture the most obvious parameter is the size of the net. Typically the larger the net the more it can learn. But larger nets require more data and are harder to train. Also a larger net means that evaluation in the engine becomes slower which means lower search depth. So it's all about finding the perfect balance. In practice this means a lot of educated guessing and trial-and-error.

This is of course a very simplified description, but hopefully it makes it a bit clearer.

**Comment by bmdanielsson** [comment] 2021-07-23 08:05
Detection of draw by insufficient material when using NNUE has been fixed.

**Comment by tissatussa** [comment] 2021-07-23 09:35
> Detection of draw by insufficient material when using NNUE has been fixed.

well done !
this is related to this issue .. i guess you just discovered this (bug) and fixed it .. indeed, my Marvin v5.1.0 NNUE keeps on playing with K+N+N vs K (which is a draw).

regarding this K+N+B vs K issue : probably an engine is not allowed to use TBs during official tournaments .. but could you program some basic code / patterns to assist the engine in finding the right "path to victory" in such basic endgames ? I'm thinking of a few winning "anchor positions" which it can try to reach !?

Btw. what is allowed during these engine-vs-engine matches ?  I'm not familiar with the concept(s) of those matches, like TCEC or the CCRL list .. Eg. what is the time format ?  What (max) hash is allowed ?  Is hash cleared before a game ?  Is pondering allowed ?  Is there a max number of threads ?  Can engine creators bring / point to their own hardware ?  I also remember an opening book is not allowed, but what about a short fixed build-in list of typical opening positions to strive for ? - is that allowed ?  Do the "tournament leaders" look into the code ?

**Comment by bmdanielsson** [comment] 2021-07-23 16:23
Yes, you could add code to the engine to help with common and/or complicated endgames. I know some engines do this. But all rating lists and tournaments I'm aware of allow at least 5-men TBs. So it's not that useful if you have TB support.

Most rating lists/tournaments use HW provided by the organizers. In those cases all engines use the same settings. In most cases pondering is not allowed. Typically engine opening books are not used, instead games are started from a predefined set of positions typically three or so moves away from the starting position. The amount of hash and number of threads varies a lot. Most rating lists like CEGT and CCRL use standard consumer HW so hash is limited to maybe 128 MB or so and 1-4 threads. TCEC on the other hand have "monster level" HW and you can use up to 128 GB hash and 172 threads (assuming the engine can handle it).

There are also some tournaments where you use your own HW and those tournaments there are typically no limitation on settings.

Normally tournament organizers don't look at source code. But some tournaments require may require that you provide source code for inspection in case of dispute. TCEC also a questionnaire that you need to fill out with information about the origins of you're engine, see https://wiki.chessdom.org/TCEC_Season_20#Questionnaire .

**Closed as completed** 2021-08-27 19:45 UTC
